---
- name: Run AVD
  hosts: cvp1
  tasks:
    - name: provision CVP with AVD configuration
      import_role:
        name: arista.avd.eos_config_deploy_cvp
      vars:
        container_root: 'FABRIC'
        configlets_prefix: 'AVD'
        state: present
        execute_tasks: false
