- name: "Run Fabric states validation"
  hosts: FABRIC
  collections:
    - arista.avd
    - arista.cvp
  tasks:

    - name: deploy configuration to device
      import_role:
        name: arista.avd.eos_validate_state
