---

fabric_name: FABRIC

# Various fabric settings

# Enable vlan aware bundles
evpn_vlan_aware_bundles: true



# There's an issue with vEOS with larger MTUs
p2p_uplinks_mtu: 1500

# BFD Settings
# bfd_multihop:
#   interval: 1200
#   min_rx: 1200
#   multiplier: 3


# # If you want to put a password on peers
# bgp_peer_groups:
#   # all passwords set to "arista"
#   evpn_overlay_peers:
#     password: Q4fqtbqcZ7oQuKfuWtNGRQ==
#   ipv4_underlay_peers:
#     password: 7x4B4rnJhZB438m9+BrBfQ==
#   mlag_ipv4_underlay_peer:
#     password: 4b21pAdCvWeAqpcKDFMdWw==


# Needed for Arista ATD Lab Environment
dns_domain: atd.lab
mgmt_interface: Management1
mgmt_interface_vrf: default
mgmt_gateway: 192.168.0.1
