---

fabric_name: FABRIC

# Various fabric settings

# Enable vlan aware bundles
evpn_vlan_aware_bundles: true


# Support 1500 byte MTU with hosts + 50 bytes for VXLAN overhead
p2p_uplinks_mtu: 1550

# BFD Settings
# bfd_multihop:
#   interval: 1200
#   min_rx: 1200
#   multiplier: 3


# # If you want to put a password on peers
# bgp_peer_groups:
#   # all passwords set to "arista"
#   evpn_overlay_peers:
#     password: Q4fqtbqcZ7oQuKfuWtNGRQ==
#   ipv4_underlay_peers:
#     password: 7x4B4rnJhZB438m9+BrBfQ==
#   mlag_ipv4_underlay_peer:
#     password: 4b21pAdCvWeAqpcKDFMdWw==


# Needed for Arista ATD Lab Environment
dns_domain: atd.lab
mgmt_interface: MGMT
mgmt_interface_vrf: default
mgmt_gateway: 192.168.0.1



l3_edge:
  p2p_links_ip_pools:
    dci_evpn_gateway: 172.31.252.0/24
  p2p_links:
    - id: 1
      ip_pool: dci_evpn_gateway
      nodes: [borderleaf1, borderleaf2]
      interfaces: [Ethernet1, Ethernet1]
      as: [65199, 65299]
      include_in_underlay_protocol: true
    - id: 2
      ip_pool: dci_evpn_gateway
      nodes: [borderleaf1, borderleaf2]
      interfaces: [Ethernet2, Ethernet2]
      as: [65199, 65299]
      include_in_underlay_protocol: true